# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml hoho

trigger:
- main

pool: Azure Pipelines

stages: 
- stage: BuildApp
  jobs: 
  - job : InstallNodeTool
    steps:
     -  task: NodeTool@0
        inputs:
          versionSpec: '8.5.1'
     - script: |
         npm install
         npm run build

        


