# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml hoho

trigger:
- main

pool: Azure Pipelines

stages: 
- stage: BuildApp
  jobs: 
  - job : InstallDependncies
    steps:
      - task: Npm@1
        inputs:
          command: 'install'
          workingDir: 'app/'
  - job : BuildApplication
    steps:
      - task: Npm@1
        inputs:
          command: 'custom'
          workingDir: 'app/'
          customCommand: 'npm run build'

