# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml hoho

trigger:
- main

pool: Azure Pipelines

stages: 
- stage: BuildApp
  jobs: 
  - job : BuildTheApplication
    steps:
      -  task: NodeTool@0
         inputs:
            versionSpec: '12.x'
      - task: Npm@1
        inputs:
          command: 'install'
          workingDir: 'app'
      - task: Npm@1
        inputs:
          command: 'custom'
          workingDir: 'app'
          customCommand: 'run build'

- stage: TestTheApplication
  jobs: 
  - job : RunUnitTests
    steps: 
      -  task: NodeTool@0
         inputs:
            versionSpec: '12.x'
      - task: Npm@1
        inputs:
          command: 'install'
          workingDir: 'app'
      - task: Npm@1
        inputs:
          command: 'custom'
          workingDir: 'app'
          customCommand: 'run test'

- stage : StaticCodeAnalysis
  jobs : 
  - job : RunSonarqube
    steps:
   
    - task: SonarQubePrepare@5
      inputs:
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'react'
        cliProjectName: 'react'
        cliSources: '.'
    - task: SonarQubeAnalyze@5
      inputs:
        jdkversion: 'JAVA_HOME_11_X64'
  
    - task: SonarQubePublish@5
      inputs:
         pollingTimeoutSec: '300'
      