- name: Install git
  ansible.builtin.apt:
    name: git
    state: present

- name: Install unzip
  ansible.builtin.apt:
    name: unzip
    state: present
    
- name: Download Azure Agent SW 
  ansible.builtin.unarchive:
    src: "https://vstsagentpackage.azureedge.net/agent/3.220.5/vsts-agent-linux-x64-3.220.5.tar.gz"
    dest: /opt
    remote_src: yes
    owner: ubuntu
    group: ubuntu

- name: Configure Azure Agent 
  become: false
  ansible.builtin.shell: ./config.sh  --acceptTeeEula --unattended --replace --agent 'AWS_EC2' --pool 'default' --url 'https://dev.azure.com/abdelrhmanhamdy/' --auth 'PAT' --token 'YOUR-TOKEN'
  args:
    chdir: /opt

- name: Run Azure Agent 
  become: false
  shell : ./run.sh 1&2>/dev/null &
  args:
    chdir: /opt
  async: 10
  poll: 0
