---
- hosts: Jfrog
  remote_user : ubuntu
  become : yes 
  
  gather_facts: false

  vars:

    - ansible_host_key_checking: False
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 100 seconds for target connection to become reachable/usable."
      wait_for_connection:
        timeout: 100

    - name: "update apt packages."
      become: yes
      apt:
        update_cache: yes

    - name: "upgrade packages"
      become: yes
      apt:
        upgrade: yes

  roles : 
    - install_run_Jfrog
